source:
  - name: mhpp
    type: json
    kwargs:
      sort_key: id
      path: data/MHPP_tc_parsed.json
  - name: pred
    type: json
    kwargs:
      sort_key: id
      path: results/20241014-gpt-pc_pred-lbl/results_merged_1.json
  - name: example
    type: yaml
    kwargs:
      sort_key: id
      path: configs/20241014/icl_examples-humaneval-yw.yaml

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: mhpp
          key: id
        - name: problem
          source: mhpp
          key: question
        - name: pseudocode
          source: pred
          key: pc_pred-lbl
        - name: tc_input
          source: mhpp
          key: tc_input
        - name: tc_output
          source: mhpp
          key: tc_output
  - name: example
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: example
          key: id
        - name: problem
          source: example
          key: question
        - name: code
          source: example
          key: solution
        - name: pseudocode
          source: example
          key: pc_lbl
        - name: tc_input
          source: example
          key: tc_input
        - name: tc_output
          source: example
          key: tc_output-lbl-bpt

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: tc_output-gen
          dependencies: []
          input_keys: [problem, pseudocode, tc_input]
          type: cot
          kwargs:
            flatten: true
            llm:
              max_tokens: 8192
              model: gpt-4o-mini
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20240924/templates/tc_output-bpt"]
