source:
  bigcodebench: !inc configs/20240930/configs/inc/source-bigcodebench.yaml
  example: !inc configs/20240930/configs/inc/source-example.yaml

dataset:
  - !inc configs/20240930/configs/inc/dataset-target.yaml
  - name: example
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: example
          key: id
        - name: problem
          source: example
          key: complete_prompt
        - name: pseudocode
          source: example
          key: pc_func

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: pc_pred-func
          dependencies: []
          input_keys: [problem]
          type: cot
          kwargs:
            flatten: true
            llm: !inc configs/llm/gpt_4o_mini-greedy.yaml
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20240930/templates/pc_pred-func"]
