source:
  bigcodebench: !inc configs/20240930/configs/inc/source-bigcodebench.yaml
  example: !inc configs/20240930/configs/inc/source-example.yaml

dataset:
  - !inc configs/20240930/configs/inc/dataset-target.yaml
  - name: example
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: example
          key: task_id
        - name: problem
          source: example
          key: complete_prompt
        - name: solution
          source: example
          key: canonical_solution
        - name: pc_lbl
          source: example
          key: pc_lbl
        - name: pc_func
          source: example
          key: pc_func
        - name: pc_nl
          source: example
          key: pc_nl

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: pseudocodes
          dependencies: []
          input_keys: [problem, solution]
          type: cot
          kwargs:
            llm: !inc configs/llm/gpt_4o_mini-greedy.yaml
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20240930/templates/pseudocode"]
