source:
  - name: CodeEditorBench
    type: huggingface
    kwargs:
      sort_key: idx
      path: m-a-p/CodeEditorBench
      split: train
      load_dataset_kwargs:
        data_files:
          - code_debug_plus.jsonl
          - code_debug_primary.jsonl

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      query: where('code_language') == 'python3'
      fields:
        - name: id
          source: CodeEditorBench
          key: idx
        - name: code_language
          source: CodeEditorBench
          key: code_language
        - name: incorrect_solutions
          source: CodeEditorBench
          key: incorrect_solutions
        - name: correct_solutions
          source: CodeEditorBench
          key: solutions

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, execute]
      type: always
    - pair: [execute, revise]
      type: loop_until_success
      kwargs:
        max_iterations: 4
    - pair: [revise, execute]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: plan
          dependencies: [skeleton]
          input_keys: [skeleton]
          type: cot
          kwargs:
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: gpt-4o
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/default/plan"]
        - name: initial_code
          dependencies: [skeleton, plan]
          input_keys: [skeleton, plan]
          type: cot
          kwargs:
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: gpt-4o
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/default/code"]
        - name: testcases
          dependencies: [skeleton]
          input_keys: [skeleton]
          type: cot
          kwargs:
            flatten: true
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: gpt-4o
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
              - type: load_python_obj
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/reflexion/testcases"]
        - name: revised_code
          dependencies: [initial_code]
          input_keys: [initial_code]
          type: assign

    - name: execute
      chains:
        - name: exec_code
          dependencies: []
          input_keys: [revised_code, testcases]
          type: cot
          kwargs:
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: gpt-4o
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/reflexion/exec_code"]
        - name: exec_result
          dependencies: [exec_code]
          input_keys: [exec_code]
          type: execute
          kwargs:
            target: exec_code
            timeout: 10
        - name: filter_failed
          dependencies: [exec_code, exec_result]
          input_keys: [exec_code, exec_result]
          type: select
          kwargs:
            src: [exec_code, exec_result]
            dst: [exec_code_failed, exec_result_failed]
            tgt: exec_result
            func: "lambda x: 'Exit Code: 0' not in x"

    - name: revise
      chains:
        - name: prev_code
          dependencies: []
          input_keys: [revised_code]
          type: assign
        - name: exec_code_failed_0
          dependencies: []
          input_keys: [exec_code_failed]
          type: get_ith
          kwargs:
            target: exec_code_failed
            index: 0
        - name: exec_result_failed_0
          dependencies: []
          input_keys: [exec_result_failed]
          type: get_ith
          kwargs:
            target: exec_result_failed
            index: 0
        - name: revised_code
          dependencies: [prev_code, exec_code_failed_0, exec_result_failed_0]
          input_keys: [prev_code, exec_code_failed_0, exec_result_failed_0]
          key_map: { exec_code_failed_0: exec_code, exec_result_failed_0: exec_result }
          type: cot
          kwargs:
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: gpt-4o
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/reflexion/revised_code"]
