source:
  - name: ClassEval
    type: huggingface
    kwargs:
      sort_key: task_id
      path: FudanSELab/ClassEval
      split: test
  - name: Generated
    type: json
    kwargs:
      path: results/ours-gpt4o-prev/gen_tc.json
      sort_key: id

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: ClassEval
          key: task_id
        - name: solution_code
          source: ClassEval
          key: solution_code
        - name: gen_tc
          source: Generated
          key: gen_tc

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: exec_code
          dependencies: []
          input_keys: [solution_code, gen_tc]
          type: custom_lambda
          kwargs:
            src: [solution_code, gen_tc]
            func: "lambda x, y: x + '\\n\\n' + y"
        - name: exec_result
          dependencies: [exec_code]
          input_keys: [exec_code]
          type: execute
          kwargs:
            target: exec_code
            timeout: 10
