source:
  - name: ClassEval
    path: FudanSELab/ClassEval
    type: huggingface
    split: test

dataset:
  - name: target
    primary_key: id
    fields:
      - name: id
        source: ClassEval
        type: ClassEval
        key: task_id
      - name: skeleton
        source: ClassEval
        type: ClassEval
        key: skeleton

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: code
          dependencies: []
          input_keys: [skeleton]
          type: cot
          kwargs:
            llm:
              max_retries: 1000000
              max_tokens: 2048
              model: llama3:70b-instruct-fp16
              platform: open_webui
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["templates/vanilla/code"]
