source:
  - name: code_contests
    type: json
    kwargs:
      sort_key: id
      path: results/20241115-pc/results_merged_1.json
  - name: example
    type: yaml
    kwargs:
      sort_key: id
      path: configs/20241115/icl_examples/codecontests.yaml

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: code_contests
          key: id
        - name: problem
          source: code_contests
          key: problem
        - name: tc_input
          source: code_contests
          key: tc_input
        - name: tc_output-gt
          source: code_contests
          key: tc_output-gt
        - name: pc_lbl-pred
          source: code_contests
          key: pc_lbl-pred

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: ranking-pc
          dependencies: [pc_lbl-pred]
          type: pairwise_ranking
          key_map:
            pc_lbl-pred: pseudocode
          output_keys: [ranking-pc]
          kwargs:
            target_key: pseudocode
            disable_icl: True
            llm:
              max_tokens: 2048
              platform: vllm
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20241115/templates/ranking-pc"]

        - name: ranking-pc-parsed
          dependencies: [ranking-pc]
          type: pairwise_ranking_parser
          output_keys: [ranking-pc-parsed]
          kwargs:
            llm:
              max_tokens: 128
              platform: vllm
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
              - type: load_json
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20241115/templates/choice_parser"]