source:
  - name: code_contests
    type: json
    kwargs:
      sort_key: id
      path: results/20240924-pc_pred-nl/parsed.json
  - name: example
    type: yaml
    kwargs:
      sort_key: id
      path: configs/20241104/icl_examples/codecontests.yaml

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: code_contests
          key: id
        - name: problem
          source: code_contests
          key: problem
        - name: solution
          source: code_contests
          key: solution
        - name: tc_input
          source: code_contests
          key: tc_input
        - name: tc_output-gt
          source: code_contests
          key: tc_output
  - name: example
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: example
          key: id
        - name: problem
          source: example
          key: question
        - name: solution
          source: example
          key: solution
        - name: tc_input
          source: example
          key: tc_input
        - name: tc_output
          source: example
          key: tc_output-lbl-bp
        - name: pseudocode
          source: example
          key: pc_lbl

graph:
  entry_point: initialize

  edges:
    - pair: [initialize, __end__]
      type: always

  nodes:
    - name: initialize
      chains:
        - name: pc_lbl-gt
          dependencies: []
          input_keys: [problem, solution]
          type: cot
          kwargs:
            flatten: true
            llm:
              max_tokens: 8192
              model: gpt-4o-mini
              platform: openai
              temperature: 0
              top_p: 1
            parsers:
              - type: code_block
            prompt:
              type: chat
              kwargs:
                body_template_paths: ["configs/20241104/templates/pc_lbl-gt"]
